version: 1.0
provider:
    name: openfaas
    gateway: http://127.0.0.1:8080
functions:
    chatgpt:
        lang: python3-http
        handler: ./chatgpt
        image: wilsonng234/chatgpt:latest
    dalle2:
        lang: python3-http
        handler: ./dalle2
        image: wilsonng234/dalle2:latest
